@WebApi_BaseHostAddress = http://localhost:5074

GET {{WebApi_BaseHostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_BaseHostAddress}}/healthcheck/
Accept: application/json

###
